Patch when no data received.
If there was not a response from the Mojang servers then an error would occur:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/player-info/node_modules/mojang/lib/_request.js:18:21)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

You can replicate by looking up a username which does not exist.